import { jsPDF } from 'jspdf';

export interface ReportForPdf {
  report_type: string;
  report_date?: string;
  file_name?: string;
  doctor_name?: string;
  hospital?: string;
  notes?: string;
  extracted_text?: string;
}

export interface LabFindingForPdf {
  name: string;
  value: number;
  unit: string;
  status: string;
  reference_range: string;
}

/**
 * Build a clean, text-based PDF health report entirely in the browser (no
 * server round-trip). Returns nothing; triggers a download of `<type>-report.pdf`.
 */
export function generateReportPdf(
  report: ReportForPdf,
  findings?: LabFindingForPdf[]
): void {
  const doc = new jsPDF({ unit: 'pt', format: 'a4' });
  const pageWidth = doc.internal.pageSize.getWidth();
  const pageHeight = doc.internal.pageSize.getHeight();
  const margin = 48;
  const contentWidth = pageWidth - margin * 2;
  let y = margin;

  const ensureSpace = (needed: number) => {
    if (y + needed > pageHeight - margin) {
      doc.addPage();
      y = margin;
    }
  };

  const line = (text: string, size: number, style: 'normal' | 'bold' = 'normal', color = '#111111') => {
    doc.setFont('helvetica', style);
    doc.setFontSize(size);
    doc.setTextColor(color);
    const wrapped = doc.splitTextToSize(text, contentWidth) as string[];
    for (const w of wrapped) {
      ensureSpace(size + 4);
      doc.text(w, margin, y);
      y += size + 4;
    }
  };

  // Header
  doc.setFillColor('#2563EB');
  doc.rect(0, 0, pageWidth, 6, 'F');
  line('MediStore — Medical Report', 20, 'bold', '#2563EB');
  y += 4;

  const typeLabel = (report.report_type || 'Report').replace(/_/g, ' ');
  line(typeLabel, 15, 'bold');
  y += 6;

  // Metadata block
  const meta: Array<[string, string | undefined]> = [
    ['Date', report.report_date ? new Date(report.report_date).toLocaleDateString() : undefined],
    ['Doctor', report.doctor_name],
    ['Hospital', report.hospital],
    ['File', report.file_name],
  ];
  for (const [label, value] of meta) {
    if (value) line(`${label}: ${value}`, 11);
  }
  y += 8;

  if (report.notes) {
    line('Notes', 13, 'bold');
    line(report.notes, 11);
    y += 6;
  }

  // Lab findings table (if provided)
  if (findings && findings.length > 0) {
    line('Lab Findings', 13, 'bold');
    y += 2;
    for (const f of findings) {
      const flag = f.status && f.status !== 'NORMAL' ? `  [${f.status}]` : '';
      const color = f.status === 'HIGH' ? '#b91c1c' : f.status === 'LOW' ? '#b45309' : '#111111';
      line(`${f.name}: ${f.value} ${f.unit} (ref ${f.reference_range})${flag}`, 11, 'normal', color);
    }
    y += 6;
  }

  if (report.extracted_text) {
    line('Extracted Text', 13, 'bold');
    line(report.extracted_text, 10, 'normal', '#333333');
  }

  // Footer note
  ensureSpace(24);
  y = pageHeight - margin + 12;
  doc.setFont('helvetica', 'normal');
  doc.setFontSize(9);
  doc.setTextColor('#888888');
  doc.text(`Generated by MediStore on ${new Date().toLocaleString()}`, margin, y);

  const safeName = (typeLabel || 'report').toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/(^-|-$)/g, '');
  doc.save(`${safeName || 'report'}.pdf`);
}
